# Generated by Django 5.0 on 2023-12-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('linkedln_url', models.URLField()),
                ('linkedln_username', models.CharField(max_length=50)),
                ('facebook_url', models.URLField()),
                ('facebook_username', models.CharField(max_length=50)),
                ('instagram_url', models.URLField()),
                ('instagram_username', models.CharField(max_length=50)),
                ('twitter_url', models.URLField()),
                ('twitter_username', models.CharField(max_length=50)),
                ('github_url', models.URLField()),
                ('github_username', models.CharField(max_length=50)),
                ('medium_url', models.URLField()),
                ('medium_username', models.CharField(max_length=50)),
            ],
        ),
    ]
