# Generated by Django 5.0 on 2023-12-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='enddate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='startdate',
            field=models.DateField(default=None, null=True),
        ),
    ]
