# Generated by Django 5.0 on 2023-12-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_education_enddate_education_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
