# Generated by Django 5.0 on 2023-12-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.TextField()),
                ('about_me', models.TextField()),
                ('my_aim', models.TextField()),
            ],
        ),
    ]
