# Generated by Django 5.0 on 2023-12-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Research',
            },
        ),
    ]
