# Generated by Django 5.0 on 2023-12-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
