# Generated by Django 5.0 on 2023-12-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_research_description_alter_research_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='type',
            field=models.CharField(choices=[('finished', 'finished'), ('ongoing', 'ongoing')], default='finished', max_length=50),
        ),
    ]
