# Generated by Django 5.0 on 2023-12-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='skill',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='type',
            field=models.CharField(choices=[('tech', 'tech'), ('mentor', 'mentor'), ('social', 'social')], default='tech', max_length=50),
        ),
    ]
