# Generated by Django 5.0 on 2023-12-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_experience_skill_experience_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='skill',
        ),
    ]
