# Generated by Django 5.0 on 2023-12-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_remove_experience_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='enddate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='startdate',
            field=models.DateField(default=None, null=True),
        ),
    ]
