# Generated by Django 5.0 on 2023-12-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_experience_enddate_experience_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
