# Generated by Django 5.0 on 2023-12-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='text_field',
            field=models.CharField(choices=[('programming_language', 'programming_language'), ('frameworks', 'frameworks'), ('libraries', 'libraries'), ('data', 'data'), ('database', 'database'), ('containers', 'containers'), ('extra', 'extra')], default='programming_language', max_length=50),
        ),
    ]
