# Generated by Django 5.0 on 2023-12-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_text_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='text_field',
            new_name='name',
        ),
    ]
