# Generated by Django 5.0 on 2023-12-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_rename_text_field_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('programming_language', 'programming_language'), ('frameworks', 'frameworks'), ('libraries', 'libraries'), ('data', 'data'), ('database', 'database'), ('containers', 'containers'), ('extra', 'extra'), ('social', 'social')], default='programming_language', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
